"""Add status column to House model

Revision ID: 45de062e8d29
Revises: b149b386e4c0
Create Date: 2025-10-21 05:05:23.307985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45de062e8d29'
down_revision = 'b149b386e4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
